### ISSUE TITLE
[BUG] support email cannot be sent 

### ISSUE THREAD

**Issue by Olzeke51** [NeonGeckoCom/skill-support_helper#79]
### Description

tried various combinations of voice & mana say-to to get a troubleshooting/support package sent.
all 4 attempts failed.
beta 18b31

### Relevant Code

text file with relevant info & log files  - first 3 attempts
[support.error.tar.gz](https://github.com/user-attachments/files/15936697/support.error.tar.gz)

### Other Notes

4th attempt failed , I had turned off the wallpaper rotation; to see if that was interfering.

**Comment by NeonDaniel** [comment]
probably the same issue as https://github.com/NeonGeckoCom/skill-weather/issues/56
